Description = "欢迎来到xshrim个人博客，个人主要专注于Kubernetes, 云原生和程序开发。"
Keywords =  "博客, 程序员, 容器, 云原生"
Subtitle = "没有伞的孩子要学会努力奔跑!"
AuthorImg = "/img/avatar.png"
AuthorName = "xshrim"
Introduce = "再平凡的人也有属于他自己的梦想!"
DateFormat = "2006-01-02"
YearFormat = "2006年"
MonthFormat = "01-02"

[Footer]
  StorageLink = "https://github.com"
  StorageName = "Github Page"
  ICPLink = ""
  ICPNo = "-"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/xshrim/"

[[Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/xshrim"

[[Links]]
  Name = "廖雪峰"
  Permalink = "https://www.liaoxuefeng.com/"
